# GitHub Actions CI/CD workflow file.
# This configuration runs tests and checks code quality on every push and pull request.

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    # Define the environment for this job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (adjust this for your project needs)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        # If you're using another language or tool, replace `npm install` with the appropriate command.

      # Step 4: Run lint checks
      - name: Run linter
        run: npm run lint
        # Ensure you have a "lint" script defined in your `package.json`.

      # Step 5: Run tests
      - name: Run tests
        run: npm test
        # Replace this with the test command for your project.
